// This file is autogenerated from QUADROTOR_CONFIG
// Autogeneration date and time: 2023-05-13 23:11:21

#ifndef QUADROTOR_CONFIG_H
#define QUADROTOR_CONFIG_H

#define QUADROTOR_CONFIG_mass:kg 0.500000
#define QUADROTOR_CONFIG_inertia_xx_kgmm2 0.005000
#define QUADROTOR_CONFIG_inertia_yy_kgmm2 0.005000
#define QUADROTOR_CONFIG_inertia_zz_kgmm2 0.010000
#define QUADROTOR_CONFIG_cog_x_m 0.000000
#define QUADROTOR_CONFIG_cog_y_m 0.000000
#define QUADROTOR_CONFIG_cog_z_m 0.000000
#define QUADROTOR_CONFIG_rotor_thrust_constant 0.000100
#define QUADROTOR_CONFIG_rotor_torque_constant 0.000001
#define QUADROTOR_CONFIG_max_rotor_speed_RPM 10000.000000
#define QUADROTOR_CONFIG_max_rotor_thrust_N 10.000000
#define QUADROTOR_CONFIG_max_rotor_torque_Nm 0.500000
#define QUADROTOR_CONFIG_rotor_1_pos_x_m 0.200000
#define QUADROTOR_CONFIG_rotor_1_pos_y_m 0.000000
#define QUADROTOR_CONFIG_rotor_1_pos_z_m 0.000000
#define QUADROTOR_CONFIG_rotor_2_pos_x_m 0.000000
#define QUADROTOR_CONFIG_rotor_2_pos_y_m 0.200000
#define QUADROTOR_CONFIG_rotor_2_pos_z_m 0.000000
#define QUADROTOR_CONFIG_rotor_3_pos_x_m -0.200000
#define QUADROTOR_CONFIG_rotor_3_pos_y_m 0.000000
#define QUADROTOR_CONFIG_rotor_3_pos_z_m 0.000000
#define QUADROTOR_CONFIG_rotor_4_pos_x_m 0.000000
#define QUADROTOR_CONFIG_rotor_4_pos_y_m -0.200000
#define QUADROTOR_CONFIG_rotor_4_pos_z_m 0.000000
#define QUADROTOR_CONFIG_attitude_max_tilt_deg 45
#define QUADROTOR_CONFIG_position_max_speed_mps 30

#endif /* QUADROTOR_CONFIG_H */
