// This file is autogenerated from QUADROTOR_CONFIG
// Autogeneration date and time: 2023-05-13 18:07:27
#ifndef QUADROTOR_CONFIG_H
#define QUADROTOR_CONFIG_H

#define QUADROTOR_CONFIG_mass 0.500000
#define QUADROTOR_CONFIG_inertia_xx 0.005000
#define QUADROTOR_CONFIG_inertia_yy 0.005000
#define QUADROTOR_CONFIG_inertia_zz 0.010000
#define QUADROTOR_CONFIG_arm_length 0.200000
#define QUADROTOR_CONFIG_propeller_thrust_constant 0.000100
#define QUADROTOR_CONFIG_propeller_torque_constant 0.000001
#define QUADROTOR_CONFIG_max_propeller_speed 10000.000000
#define QUADROTOR_CONFIG_max_thrust 10.000000
#define QUADROTOR_CONFIG_max_torque 0.500000

#endif /* QUADROTOR_CONFIG_H */
