
/**
 * @author  Burak Yueksel
 * @date    13 May 2023
 * @brief   Config libraries
 * @addtogroup CONFIG
 **/

#include "config.h"
#include <time.h> // for the date and time  stamp of auto config file generation

// Generate header file from JSON configuration
void generate_header_from_json_basic(const char* input_file, const char* output_file, const char* header_guard)
{
    // Read JSON input file
    FILE* fp = fopen(input_file, "r");
    if (!fp) {
        fprintf(stderr, "Error: Failed to open input file %s\n", input_file);
        return;
    }
    char line[MAX_LINE_LENGTH];
    size_t len = 0;
    char* json_str = NULL;
    while (fgets(line, MAX_LINE_LENGTH, fp)) {
        len += strlen(line);
        json_str = realloc(json_str, len + 1);
        strcat(json_str, line);
    }
    fclose(fp);

    // Get the current time
    time_t now = time(NULL);
    struct tm* t = localtime(&now);
    // Format the time as a string
    char datetime[20];
    strftime(datetime, sizeof(datetime), "%Y-%m-%d %H:%M:%S", t);

    // Parse JSON input string
    struct json_object* json = json_tokener_parse(json_str);

    // Generate header file from JSON
    fp = fopen(output_file, "w");
    if (!fp) {
        fprintf(stderr, "Error: Failed to open output file %s\n", output_file);
        return;
    }

    fprintf(fp, "#ifndef %s\n", header_guard);
    fprintf(fp, "#define %s\n\n", header_guard);
    fprintf(fp, "// This file is autogenerated from %s\n", input_file);
    fprintf(fp, "// Autogeneration date and time: %s\n", datetime);
    json_object_object_foreach(json, key, val) {
        const char* type = json_type_to_name(json_object_get_type(val));
        fprintf(fp, "extern const %s %s;\n", type, key);
    }
    fprintf(fp, "\n#endif /* %s */\n", header_guard);
    fclose(fp);

    // Clean up
    json_object_put(json);
    free(json_str);
}

void generate_header_from_json(const char* json_file, const char* header_file_name, const char* struct_name) {
    struct json_object *json;
    FILE* header_file = fopen(header_file_name, "w");

    if (!header_file) {
        perror(header_file_name);
        exit(EXIT_FAILURE);
    }

    // Get the current time
    time_t now = time(NULL);
    struct tm* t = localtime(&now);
    // Format the time as a string
    char datetime[20];
    strftime(datetime, sizeof(datetime), "%Y-%m-%d %H:%M:%S", t);

    fprintf(header_file, "// This file is autogenerated from %s\n", struct_name);
    fprintf(header_file, "// Autogeneration date and time: %s\n\n", datetime);

    fprintf(header_file, "#ifndef %s_H\n", struct_name);
    fprintf(header_file, "#define %s_H\n\n", struct_name);

    json = json_object_from_file(json_file);

    if (!json) {
        fprintf(stderr, "Error parsing JSON file '%s'\n", json_file);
        fclose(header_file);
        exit(EXIT_FAILURE);
    }

    json_object_object_foreach(json, key, val) {
        char *value_string;
        switch (json_object_get_type(val)) {
            case json_type_boolean:
                value_string = json_object_get_boolean(val) ? "1" : "0";
                break;
            case json_type_double:
                {
                    double value = json_object_get_double(val);
                    value_string = malloc(sizeof(char) * 20);
                    snprintf(value_string, 20, "%f", value);
                    break;
                }
            case json_type_int:
                {
                    int value = json_object_get_int(val);
                    value_string = malloc(sizeof(char) * 20);
                    snprintf(value_string, 20, "%d", value);
                    break;
                }
            case json_type_null:
                // unsupported type
                fprintf(stderr, "Unsupported JSON type for key '%s': null\n", key);
                continue;
            case json_type_object:
                // unsupported type
                fprintf(stderr, "Unsupported JSON type for key '%s': object\n", key);
                continue;
            case json_type_array:
                // unsupported type
                fprintf(stderr, "Unsupported JSON type for key '%s': array\n", key);
                continue;
            case json_type_string:
                value_string = json_object_get_string(val);
                break;
        }

        fprintf(header_file, "#define %s_%s %s\n", struct_name, key, value_string);
        if (json_object_get_type(val) == json_type_double || json_object_get_type(val) == json_type_int) {
            free((void*) value_string);
        }
    }

    fprintf(header_file, "\n#endif /* %s_H */\n", struct_name);

    fclose(header_file);
    json_object_put(json);
}

